#!/bin/sh
# ci_post_clone.sh — runs automatically on Xcode Cloud after the repo is cloned.
# Generates Secrets.xcconfig so the build can find it.
# The Chicago Data Portal app token is a rate-limiting key, not a billing secret.

set -e

SECRETS_PATH="$CI_WORKSPACE/SummertimeChi/Resources/Secrets.xcconfig"

cat > "$SECRETS_PATH" <<EOF
// Auto-generated by ci_post_clone.sh — do not edit manually.
CHICAGO_APP_TOKEN = ${CHICAGO_APP_TOKEN:-tP5KQ60ggGEdOvvmMOgvWkK0e}
EOF

echo "Secrets.xcconfig written to $SECRETS_PATH"
